/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package catalogo.personajes;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Lindsey Camargo
 */
public class Lienzo extends javax.swing.JPanel implements ActionListener{
    
    public Personaje[] personajes;
    private Image img;
    public Timer timer = new Timer(1,this);
    public int p=0;
    public int velocidad;
    public Premios premios;
    
    public Lienzo(Personaje []personajes,int velocidad, Premios premios) {
        this.personajes=personajes;
        this.timer=new Timer(velocidad,this);
        this.premios=premios;
        initComponents();
        setSize(600,500);
        setFocusable(true);
        addKeyListener(new teclado());
        timer.start();
    }
    public Lienzo(int[] personajes) {
        setBackground(Color.WHITE);
        setSize(600,600);
        setFocusable(true);
        addKeyListener(new teclado());
        timer.start();
    }

    @Override
    public void paint (Graphics g){
            super.paint(g);
            
            Graphics2D g3 = (Graphics2D)g;
            ImageIcon fot = new ImageIcon("imagenes/fondo.jpg");
            img = fot.getImage();
            g3.drawImage(img, 0,0, null);
            
            for(int i=0;i<personajes.length;i++){
//            JLabel[] personajes;
//            personajes = new JLabel[5]; 
            Graphics2D g2 = (Graphics2D)g;
//            Graphics2D g1 = (Graphics2D)g;
            g2.drawImage(personajes[i].tenerImagen(), personajes[i].tenerX(), personajes[i].tenerY(),null);
            //g1.drawImage(personajes[0], 10, 20, Color.yellow, this);
            }
            Graphics2D g4 = (Graphics2D)g;// graficando premios 
//            Graphics2D g1 = (Graphics2D)g;
            g4.drawImage(premios.tenerImagen(), premios.tenerX(), premios.tenerY(),null);    
            
    }
    

    @Override
    public void actionPerformed(ActionEvent ae) {
        for (int i=0;i<personajes.length;i++){
            personajes[i].mover();
            
                if (premios.tenerX()==personajes[i].tenerX() && premios.tenerX()==personajes[i].tenerX())  {
                    JOptionPane.showMessageDialog(this, "Adquiriste poder");
                    personajes[i].agegarobservador(premios);
                    personajes[i].aviso(10);
                }
                
        repaint();
//        info();
        }
    }
    
    private class teclado extends KeyAdapter{
        public void keyPressed(KeyEvent e){
            for (int i=0;i<personajes.length;i++){
        personajes[i].keyPressed(e);
        }
           
        }
        public void keyReleased(KeyEvent e){
            for (int i=0;i<personajes.length;i++){ 
            personajes[i].keyReleased(e);
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
