/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package catalogo.personajes;

import java.awt.Canvas;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URL;
import javax.swing.JPanel;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Lindsey Camargo
 * y 
 */
public class VCreado extends javax.swing.JFrame {
    public Personaje[] personajes;
    public ArrayList<Lienzo> lienzos;
    int velocidad;
    
  

    
    public VCreado(Personaje[] personajes, int velocidad) {
        this.velocidad=velocidad;
        //this.lienzos = new ArrayList<Lienzo>(personajes.length);
        initComponents();
        this.personajes=personajes;
        setSize(600,600);
        setTitle("Personaje creado"); 
//        for(int i=0;i<personajes.length;i++){
            System.out.println(personajes);
        Premios premios = new Premios();
            //lienzos.add(lienz/--ito);
//            new Lienzo(personajes);
        add(new Lienzo(personajes,velocidad,premios));
        JButton Confg = new JButton("Configuracion");
        Confg.setBounds(225, 510, 150, 40);
        ActionListener Click = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) { 
                  Originator originator =  new Originator();
                  CareTaker caretaker = new CareTaker();
                  VConfiguraciones vc = new VConfiguraciones(personajes,velocidad,originator,caretaker);
                  vc.setVisible(true);
                  vc.setLocationRelativeTo(null);
                  }
            
        };
        Confg.addActionListener(Click);
        this.add(Confg);
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

   
